### ISSUE TITLE
Ehitise infohalduse strateegia ülesehitus

### ISSUE THREAD

**Issue by tormi** [e-ehitis/raamistik#33]
https://github.com/e-ehitis/raamistik/blob/master/ehitiste_infohalduse_strateegia.md

**Comment by tormi** [comment]
Sulgen, sest BIM töörühm ei võtnud Github'i kasutusele.

**Comment by wipsise** [comment]
Ilmselt töörühmas ei ole igapäevaseid programmeerijaid, kes seda githubi lahti hammustaksid. Mulle on ka jätkuvalt segane, kuidas see töö siin peaks käima. Ehk oleks abiks miski juhend või briifing?

**Comment by tormi** [comment]
Sisuliselt ei ole BIM töörühm jah seda töövormi kasutama hakanud, kasutatakse google docsi. Tõsi ta on, et Github vajab alguses veidi juhendamist, olen seda hea meelega nõus pakkuma.

Oleme riigi kinnisvaravaldkonna infohalduse tegevuskava koostamisel minemas uuele katsele, https://github.com/kinnisvara/infohalduse-tegevuskava.

**Comment by tormi** [comment]
Kõige operatiivsemalt saan viimati viidatud projekti kohta siin tagasisidet anda: https://gitter.im/kinnisvara/infohalduse-tegevuskava
